Mobile second section
AnelisaDee/Portfolio pull request #3
Opened 2022-10-28 19:18 UTC by AnelisaDee

**This is a portfolio mobile version.**
This project is developed using best practice of linters. I created the sections of this mobile website using the template found in Figma App.

**Project Requirements**

 **Build the middle section of the mobile website**

- I used css grids and flexbox container for the middle section in order for it to be more responsive in any device.

- Styled it according to the template I chose.

- The 'work' and 'About Me' section

- The content of the body is container in one grid container

- Elements inside the grid are in flexbox

- Added 2 space indentation inside the .css file

2022-10-28 21:23 UTC, mwanawabangona requested changes
Hi @AnelisaDee,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

- [ ] `required`
- [ ] Please add more cards you have only made a few please add just as the figma template has 7 cards

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 21:23 UTC, mwanawabangona commented on index.html
> +        <a href="#">See Project</a>
- [ ] `required`
- [ ] Good job so far 👏 
- [ ] Please make you increase some space on `most recent works` also and an underline like the Figma template
- [ ] Also consider making sure that the `see project` button, the words don't fold like the Figma template
- [ ] You may also consider giving the card the right background color the Figma template
- [ ] please screenshots below


`your template`
![image](https://user-images.githubusercontent.com/66230306/198729406-39688a9d-bf34-490c-b05c-9c9e5f47b635.png)


`figma template`
![image](https://user-images.githubusercontent.com/66230306/198728518-010bb9d6-9d59-4c4b-a198-ecb4977ba066.png)

2022-10-28 21:23 UTC, mwanawabangona commented on index.html
> +      </div>
- [ ] `required`
- [ ] please consider a space between the 2 cards the Figma template
- [ ] also you may consider making the button stretch all the way as the Figma template
- [ ] please see screenshots belows

`your template`
![image](https://user-images.githubusercontent.com/66230306/198733115-7c5cb08a-833a-4af8-8ef9-69ed297201d0.png)

`figma tempate`
![image](https://user-images.githubusercontent.com/66230306/198734571-05c33656-a893-4fe6-8d47-c1093f7dc87b.png)

2022-10-29 02:05 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️   

## Hi @AnelisaDee 👋,

You've done well implementing some of the requested changes 👏 , but there are still some which haven't been addressed yet.

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Good folder structure.
✔️ Added some changes requested by the previous reviewer.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 02:05 UTC, Gopxfs commented on index.html
> +      </div>
As requested by the previous reviewer:
Please update your project cards to be equal to the ones on Figma. Kindly notice that Figma template has 6 cards:
![image](https://user-images.githubusercontent.com/42799579/198760048-9f448277-aabe-4d70-a6fc-9cad8a1da82d.png)

While your project only has one:
![image](https://user-images.githubusercontent.com/42799579/198760156-b974a1a6-e446-468b-b910-8de2ab03b8dd.png)
> Keep in mind that this project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉.

2022-10-29 02:05 UTC, Gopxfs commented on style.css
> +}
As requested by the previous reviewer, please make sure that your button text is displayed only in one line, as in the Figma design 😃:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/198762926-c7b2418f-0db8-4739-b6e7-ae68be648072.png)  | ![image](https://user-images.githubusercontent.com/42799579/198761334-4e0e5695-bb04-4321-b193-33cf1c164b06.png)  |

2022-10-29 02:05 UTC, Gopxfs commented on index.html
> +      </div>
Great job adding the line as requested! To fit with the original design, please make sure that it looks like the one in the template:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/198763932-879bcef7-4d4a-4fbf-98c4-b75a09f69784.png)  | ![image](https://user-images.githubusercontent.com/42799579/198763721-82d48af7-3bfd-4518-8d26-01727b158578.png)  |

2022-10-29 02:05 UTC, Gopxfs commented on style.css
> +}
Amazing job adjusting the margin and the button width 😄! Please remove the underline on the button text to make it fit the one in Figma 😉.
![image](https://user-images.githubusercontent.com/42799579/198765765-225b8cfd-8127-41a5-a3b2-8da57485aba3.png)

2022-10-29 05:29 UTC, TuyishimireEric requested changes
# Status: REQUEST CHANGES :recycle: 
## Hi @AnelisaDee    :hand: :hand: 
I am @tuyishimireeric your reviewer for this PR :man_beard:

Great work so far! 👏
Thank you for implementing most of the required changes by the previous reviewer 👏  however, there are some issues that you still need to work on to go to the next project, but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)


## To highlight 🎯

:heavy_check_mark:  Gitflow used. :+1: 
:heavy_check_mark: No Linter errors :+1: 
:heavy_check_mark: Descriptive commit messages :+1: 

## Required Changes ♻️

- [ ] Please you still have a small issue on your button, it does look like that of figma design
![image](https://user-images.githubusercontent.com/102757126/198815458-2b92e3d7-7d0b-48dc-89bb-38b218f81372.png)
Simply remove ```letter-spacing: 0.03em;``` in your css codes :joy: only this will make your button like that of Figma design. :+1:  
![image](https://user-images.githubusercontent.com/102757126/198815526-1dc8c5b4-be1c-47a3-90b4-2c95cba4cbe3.png)


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 05:29 UTC, TuyishimireEric commented on style.css
> +}
- [ ] Good job so far! :clap: but as requested by the previous code reviewer,  your button text should look like that of Figma design :smile:  you only need to remove ```letter-spacing: 0.03em;``` to put your text on one line in your button :+1:

2022-10-29 07:52 UTC, OyePriscilla approved these changes
# Hi @AnelisaDee  😄 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
The commit messages are meaningful ✅
Linters are working properly ✅
Github flow observed ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @oyepriscilla in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 10:01 UTC, merged