Desktop version
AnelisaDee/Portfolio pull request #6
Opened 2022-11-05 17:00 UTC by AnelisaDee

**Project Description**

- Used media queries to make sure that your website displays correctly on desktop screens.
- In order to lay out the elements on the page, I used Grid and Flexbox.

2022-11-05 17:24 UTC, omarsalem7 requested changes
Hi @AnelisaDee 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper title and description. ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 17:24 UTC, omarsalem7 commented on index.html
>        </div>
- [ ] Kindly consider adding appropriate padding and margin to match your design like the one in the Figma

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/200132690-73a5bd4f-a841-44bf-b719-87fbaf76ff57.png) | ![image](https://user-images.githubusercontent.com/53402600/200132678-6389136b-5998-48e5-9c76-d0a43685f6b6.png)|

2022-11-05 17:24 UTC, omarsalem7 commented on index.html
> +        <div class="project-content">
- [ ] Also consider making project cards like the one in the template in height and width and also fix height for it in the mobile version and also make sure overlay content.

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/200132814-e7a241b1-b13c-4c82-890a-36561ae5785a.png)  | ![image](https://user-images.githubusercontent.com/53402600/200132795-ee48d786-d52e-43f7-9ffe-26a86bd8270b.png) |

2022-11-05 17:24 UTC, omarsalem7 commented on index.html
>  </body>
- [ ] Kindly consider fixing the design of the contact to match the Figma template.

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/200133018-7147ada7-2091-4200-b1e5-4069a86deade.png)  | ![image](https://user-images.githubusercontent.com/53402600/200133004-d15c16a0-f647-415d-895d-69831e75a11a.png) |

2022-11-08 11:17 UTC, fobadara approved these changes
Hi @AnelisaDee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 09:32 UTC, sajid-munawar approved these changes
### Hi @AnelisaDee , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.

> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 11:25 UTC, merged